"""add_user_profile_fields

Revision ID: 39928b414845
Revises: cb597e98746b
Create Date: 2026-04-01 16:48:05.732717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39928b414845'
down_revision: Union[str, None] = 'cb597e98746b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_tips', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('financial_tips', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('occupation', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('annual_income', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=2), nullable=True))
    op.add_column('users', sa.Column('marital_status', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('dependents', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('financial_goals', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'financial_goals')
    op.drop_column('users', 'dependents')
    op.drop_column('users', 'marital_status')
    op.drop_column('users', 'state')
    op.drop_column('users', 'annual_income')
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'date_of_birth')
    op.alter_column('financial_tips', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('financial_tips', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
